# Generated by Django 3.2.9 on 2022-06-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heyurl', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='click',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='url',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
    ]
