# Generated by Django 3.2.9 on 2022-06-29 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heyurl', '0003_auto_20220629_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_clicks', to='heyurl.url'),
        ),
    ]
